version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    command: >
      bash -c "
        chmod 400 /data/mongo.key &&
        (sleep 3 &&
          mongosh --eval 'rs.initiate()' &&
          mongosh admin --eval "'"'"
            db.createUser( { user: 'root', pwd: 'example', roles: [ { role: 'root', db: 'admin' } ] });
            "'"'" &) &&
        /usr/bin/mongod --bind_ip_all --replSet rs0 --keyFile /data/mongo.key"
    volumes:
      - ./mongo.key:/data/mongo.key

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
